[package]
name = "algorithm"
version = "0.1.0"
edition = "2021"
authors = ["tickbh <tickdream125@hotmail.com>"]
description = " http https proxy by rust"
repository = "https://github.com/tickbh/wmproxy"
license = "Apache-2.0"
keywords = ["http2", "socks5", "websocket", "nginx", "proxy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
